trivia_otazky = [{"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Cold War ended with Joseph Stalin&#039;s death.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The two atomic bombs dropped on Japan by the United States in August 1945 "
                              "were named &#039;Little Man&#039; and &#039;Fat Boy&#039;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "Joseph Stalin&#039;s real name was Ioseb Bessarionis dze Dzugashvili.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Sargon II, a king of the Neo-Assyrian Empire, "
                              "was a direct descendant of Sargon of Akkad.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Assyrian king Sennacherib&#039;"
                              "s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say it"
                              "&quot; is a quote from French philosopher Voltaire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "United States President John F. Kennedy was assassinated "
                              "during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Former United States Presidents John Adams and Thomas Jefferson "
                              "died within hours of each other.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America declared their independence from the British Empire"
                              " on July 4th, 1776.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Abraham Lincoln was the first U.S. President "
                              "to be born outside the borders of the thirteen original states. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The USS Missouri (BB-63) last served in the Korean War.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Kublai Khan is the grandchild of Genghis Khan?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America was the first country to launch a man into space.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Franz Joseph I was the last emperor of Austria.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}
                 ]
